content_before:
  default: "<strong>Donations progress</strong>"
  type: string
content_after:
  default: ""
  type: string
progress_bar_width:
  default: 50%
  type: string
progress_bar_height:
  default: 10px
  type: string
max_value:
  default: 300
  type: integer
current_value:
  default: 150
  type: integer
value_display:
  default: "{percentage}%"
  type: string
hide_when_full:
  default: false
  type: bool
outlet_name:
  default: "above-main-container"
  type: string
display_on_mobile:
  type: bool
  default: true
display_on_homepage:
  type: bool
  default: true
url_must_contain:
  type: list
  list_type: simple
  default: /latest|/categories|/new|/unread|/top*|/tag/*|/tags/*|/c/*|/t/*
progress_bar_color:
  type: string
  default: "var(--tertiary)"
